# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'base_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.artist_view = QtWidgets.QPushButton(self.centralwidget)
        self.artist_view.setObjectName("artist_view")
        self.horizontalLayout.addWidget(self.artist_view)
        self.album_view = QtWidgets.QPushButton(self.centralwidget)
        self.album_view.setObjectName("album_view")
        self.horizontalLayout.addWidget(self.album_view)
        self.song_view = QtWidgets.QPushButton(self.centralwidget)
        self.song_view.setObjectName("song_view")
        self.horizontalLayout.addWidget(self.song_view)
        self.playlist_view = QtWidgets.QPushButton(self.centralwidget)
        self.playlist_view.setObjectName("playlist_view")
        self.horizontalLayout.addWidget(self.playlist_view)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.song_list = QtWidgets.QListWidget(self.centralwidget)
        self.song_list.setObjectName("song_list")
        self.verticalLayout.addWidget(self.song_list)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.artist_view.setText(_translate("MainWindow", "Artists"))
        self.album_view.setText(_translate("MainWindow", "Albums"))
        self.song_view.setText(_translate("MainWindow", "Songs"))
        self.playlist_view.setText(_translate("MainWindow", "Playlists"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
